-- CHORDS: 176 chord pads on 11 pages, for the OXI E16 (firmware >= 1.2.0)
--
-- Pages 1-11: each page is one chord set (a mood), 16 hand-voiced chords.
--   Push a pad to play its chord (the E16 reports pushes on release). Labels show chord names, minor chords with a
--   lowercase root (f#11 = F#m11, s = sus, a9 = add9, h7 = half-dim); the ring lights
--   while the chord sounds (its fill follows the bass note). The header shows
--   the set's name.
-- Page 12, settings: 1 transpose (root key, -12..+12) | 2 octave | 3 velocity |
--   4 gate (Hold = until the next pad; pushing the same pad again stops) |
--   5 strum (ms between notes) | 6 strum direction | 7 MIDI channel |
--   8 output port. Push encoder 1 = all notes off.
--
-- Chords come from the Impressive Chords sets (github.com/mestela/
-- schwung-impressive-chords); tools/make_chords.py picks the 11 sets and
-- writes the data block below. Settings persist in scene variables:
-- tr oct vel gate strum dir ch out.

--@assign id=17 abbr="Pad1"  name="Pad 1"  p=true g=1
--@assign id=18 abbr="Pad2"  name="Pad 2"  p=true g=2
--@assign id=19 abbr="Pad3"  name="Pad 3"  p=true g=3
--@assign id=20 abbr="Pad4"  name="Pad 4"  p=true g=4
--@assign id=21 abbr="Pad5"  name="Pad 5"  p=true g=5
--@assign id=22 abbr="Pad6"  name="Pad 6"  p=true g=6
--@assign id=23 abbr="Pad7"  name="Pad 7"  p=true g=7
--@assign id=24 abbr="Pad8"  name="Pad 8"  p=true g=8
--@assign id=25 abbr="Pad9"  name="Pad 9"  p=true g=9
--@assign id=26 abbr="Pd10"  name="Pad 10" p=true g=10
--@assign id=27 abbr="Pd11"  name="Pad 11" p=true g=11
--@assign id=28 abbr="Pd12"  name="Pad 12" p=true g=12
--@assign id=29 abbr="Pd13"  name="Pad 13" p=true g=13
--@assign id=30 abbr="Pd14"  name="Pad 14" p=true g=14
--@assign id=31 abbr="Pd15"  name="Pad 15" p=true g=15
--@assign id=32 abbr="Pd16"  name="Pad 16" p=true g=16
--@assign id=33 abbr="Trns" name="Transpose"    l=0 h=127 manual=true g=17
--@assign id=49 abbr="Trns" name="All notes off" p=true g=17
--@assign id=34 abbr="Oct"  name="Octave"       l=0 h=127 manual=true g=18
--@assign id=35 abbr="Vel"  name="Velocity"     l=0 h=127 manual=true g=19
--@assign id=36 abbr="Gate" name="Gate"         l=0 h=127 manual=true g=20
--@assign id=37 abbr="Strm" name="Strum"        l=0 h=127 manual=true g=21
--@assign id=38 abbr="Dir"  name="Strum direction" l=0 h=127 manual=true g=22
--@assign id=39 abbr="Chan" name="MIDI channel" l=0 h=127 manual=true g=23
--@assign id=40 abbr="Out"  name="Output port"  l=0 h=127 manual=true g=24

-- D: one token per pad, space separated: root pitch class ("A" = C ... "L" = B,
-- "-" = unnamed), suffix index (SUF[byte - 47]), then notes as bytes (note + 11).
-- T: page titles separated by "|".
-- BEGIN CHORD DATA (generated by tools/make_chords.py)
-- pages: Cine,ChHo,GoSo,NeSo,LoR,InJa,DeTe,LuPa,PoPi,Impr,SaBa,Set
local D = [=[GE5ACDHK GH5FHKOP GE8DHKMO HD6AFIP J9<CKOP E9?CFJO D28ADJM CD=DHKMP B:<CFK L?>HMR JD8DHKOPR E6?CFHKO BF0<FJMR GH5CDHKR G@8AOPT E9:FJKOR HH6BEGLP -0:CIJOQ D0>BEJN DO9>DIN KL9=@DGILN HF6@GILP H@=BIPQ DL2EGIJLN DD>ELNQU I97CGJN KL6EGINPQ K69EILN H@6BDEI HH9@DGLN JH;DFIN -07>CGIL CF=DGKNPS FD@GKNPS HFBDILPS DO>DIJNQ CH=@DGKN CE=@DGKL JH8BFGIKN HE9DEILN CF=DGKNS KD9DILPS JH8FGIN -0<BGLP C>=DGN HJ@FKLNP K99@EILP DO>BEIP D:2EHM I17FJO L9:EJM -09CIM DE2AHL EA5?CH IF7AEH K89CI L9:AEJ K:9@CH G95EHL K:9CH D12AE G95@EH IF7AEHJ -0:HMQ BF7>AFHM EH6ADIK LH:ADIKPT CL=AFHK G85AEHK CA:?ADIP EF3AFIP HD8DIMNR C?5?DIKP H96BFIM G15DHP C6=AFIMR GE5?CDHKP HD6=DFMR L::ADFIM GH5CDFHK EH3?BIMP JE;?BDFK JE8?BFGKP LF:ADFHK EF3ADIP HD6ABIPR JE8?FGKNS CH4BGKU EE?BFIMR AD;BFIKN LE:AHIMP EE?ABFIM HJ4@BDFIK HF6@DGILP JH8?FGIN AD;?FIKN JE,8BFGK AE/;EIJN IE+7AEFJ EE3?IMNR KE-9CGHL CE1=GKLP GE5AKOPT FE4@JNOS -0+7BFJOQ J@,8DGKPR G@)5DHMO D@5JLMQ GA)7HJOQ -0+7IKPR JA,:KMRT E@.:FKMN I?7>EG -0;CHJ -0>CJN B9@GHO BDCHJLS GOAGHLQ D?>JLN -0<GJO K>CLQV KFELOSV CFISWZ B9HOSX I?CQSV[ KEEOST[ FH@NOQVZ K?ILQSX K09@EIL F08@DGL H16=EIN C:18DGL D029EJN F04;DGLP H16=EINQ C118DILP D62;GJNS F04;GLP H16=INQ K09@IU K0-LQUX F08PSX H16QUZ FA4PUZ B0<CHLO -08DJO -09IMP G95HLQ H;6IMQ JF8IKNR EA:?AHKOR E??ACFKMR JA?DFHMR C3=AEIMQ D?>JLNQ K@9GHLQ B00CHLO A3/GKO L=:FILO E8?FIKOR C:=LPSU AA=GKP HEBILPQUX -0>DIJP KLBINPQS FA@GLNPSU D0>BEJNQ -0AGLQU A@;GIJNS D9>BJNQU F6@GILPS II<CGNOQ AH>GILQ HHBEILPS DA@GJLNS -0?EKOQU]=]
local T = [=[Cinematic|Chill House|Gospel Soul|Neo Soul Minor|Lofi R&B 1|Indie Jazz|Detroit Techno|Lush Pads|Pop Piano|Impressionist|Sad Ballads]=]
local SUF = {"", "m", "o", "+", "s2", "s4", "6", "m6", "7", "M7", "m7", "mM7", "h7", "o7", "7s", "a9", "ma9", "69", "m69", "9", "M9", "m9", "9s", "11", "m11", "M11", "13", "m13", "M13", "7b9", "7#9", "M7#11", "m7b9", "5"}
-- END CHORD DATA

local DT = 20.1            -- real update period: firmware fires after > 20 ms
local FULL = 16383
local C_ON, C_HIT = 0, 50  -- LED color: index into the app's 100-color palette
local SETP = 12            -- settings page; pads are on pages 1-11
local NN = "C C#D D#E F F#G G#A A#B "

-- Settings (page 12, ids 33-40). Gate is in 100 ms (0 = Hold), strum in 10 ms.
local SN = {"tr", "oct", "vel", "gate", "strum", "dir", "ch", "out"}
local SV = {0, 0, 100, 0, 0, 0, 1, 0}
local LO = {-12, -2, 1, 0, 0, 0, 1, 0}
local HI = {12, 2, 127, 40, 20, 1, 16, 15}

local H, nh = {}, 0        -- notes sounding
local Q, qi, qn, qt = {}, 1, 0, 0   -- strum queue: notes, next, count, ms to next
local cur, left = 0, 0     -- sounding pad (1-176); ms until release (0 = hold)
local title, shown         -- pending / displayed header text

local function clamp(v, lo, hi)
  return v < lo and lo or v > hi and hi or v
end

local function nname(n)
  local k = n % 12 * 2 + 1
  return (NN:sub(k, k + 1):gsub(" ", ""))
end

-- Start and end of pad k's token in D (k = 1-176), or nil past the end.
local function tok(k)
  local s = 1
  for _ = 2, k do
    s = D:find(" ", s, true)
    if not s then return end
    s = s + 1
  end
  return s, (D:find(" ", s, true) or #D + 1) - 1
end

local function label(s, e)
  local r = D:byte(s)
  if s + 1 >= e then return "" end
  if r == 45 then return nname(D:byte(s + 2) - 11 + SV[1]) .. "?" end
  local n, x = nname(r - 65 + SV[1]), SUF[D:byte(s + 1) - 47]
  if x:sub(1, 1) == "m" then n, x = n:lower(), x:sub(2) end   -- minor: "f#11"
  return (n .. x):sub(1, 4)
end

local function send(n, v) midi.sendMidi(SV[8], 0, 0x8F + SV[7], n, v) end

local function offAll()
  for i = 1, nh do send(H[i], 0) end
  nh, qn, cur = 0, 0, 0
end

local function setTitle(s)
  if s ~= shown then
    page.resetTitle()                 -- title freeze workaround: set on next tick
    title, shown = s, s
  end
end

-- Ring of pad k, if its page is showing.
local function drawPad(k)
  if k < 1 or (k - 1) // 16 + 1 ~= controller.getPage() then return end
  local s, e = tok(k)
  local v = s and s + 1 < e and (D:byte(s + 2) - 11 - 24) * FULL // 72 or 0
  leds.updateByIndex((k - 1) % 16 + 1, clamp(v, 0, FULL), cur == k and C_HIT or C_ON)
end

local function drawAll(pg)
  pg = pg or controller.getPage()
  if pg == SETP then
    for k = 1, 8 do
      local v = SV[k]
      leds.updateByIndex(k, (v - LO[k]) * FULL // (HI[k] - LO[k]), C_ON)
      slots.update(k, k == 1 and (v > 0 and "T+" or "T") .. v or k == 2 and (v > 0 and "Oc+" or "Oc") .. v
        or k == 3 and "V" .. v or k == 4 and (v == 0 and "Hold" or v // 10 .. "." .. v % 10 .. "s")
        or k == 5 and "S" .. v * 10 or k == 6 and (v == 1 and "Down" or "Up")
        or k == 7 and "Ch" .. v or v == 0 and "All" or "O" .. v)
    end
    for k = 9, 16 do
      leds.updateByIndex(k, 0, C_ON)
      slots.update(k, "")
    end
    setTitle("Chord settings")
  elseif pg < SETP then
    local s = tok((pg - 1) * 16 + 1)
    for i = 1, 16 do
      local e = s and (D:find(" ", s, true) or #D + 1) - 1
      slots.update(i, s and label(s, e) or "")
      drawPad((pg - 1) * 16 + i)
      s = e and e + 2 <= #D and e + 2 or nil
    end
    local n = 1
    for t in T:gmatch("[^|]+") do
      if n == pg then setTitle(t) end
      n = n + 1
    end
  end
end

-- Play pad k: queue its notes for the strum.
local function play(k)
  local was = cur
  offAll()
  drawPad(was)
  if was == k and SV[4] == 0 then return end   -- Hold: same pad again stops
  local s, e = tok(k)
  if not s or s + 1 >= e then return end
  qn = 0
  for i = s + 2, e do
    qn = qn + 1
    Q[qn] = clamp(D:byte(i) - 11 + SV[1] + SV[2] * 12, 0, 127)
  end
  if SV[6] == 1 then                   -- strum down: reverse the order
    for i = 1, qn // 2 do Q[i], Q[qn + 1 - i] = Q[qn + 1 - i], Q[i] end
  end
  qi, qt, cur, left = 1, 0, k, SV[4] * 100
  drawPad(k)
end

function system.update()
  if title then page.setTitle(title); title = nil end
  while qi <= qn and qt <= 0 do        -- strum: send due notes
    send(Q[qi], SV[3])
    nh = nh + 1
    H[nh], qi, qt = Q[qi], qi + 1, qt + SV[5] * 10
  end
  qt = qt - DT
  if left > 0 then
    left = left - DT
    if left <= 0 then
      local k = cur
      offAll()
      drawPad(k)
    end
  end
end

-- Turn ids 33-40 change the settings (page 12). Push ids 17-32 play pads on
-- pages 1-11; 49 is all notes off.
function controller.onEncoderTurn(e)
  local id, d = e.id, e.increment
  -- 0 = not a physical turn (recorder, random, group); 255 = non-script control
  if d == 0 or id < 33 or id > 40 then return end
  controller.set(id, "v", 8192)       -- keep manual encoders off their end stops
  local k = id - 32
  SV[k] = clamp(SV[k] + (k == 3 and d or d > 0 and 1 or -1), LO[k], HI[k])
  var.set(SN[k], SV[k])
  if k == 7 or k == 8 then offAll() end
  drawAll(e.page)
end

function controller.onEncoderPress(e)
  if e.id == 49 then
    offAll()
    midi.sendCC(SV[8], SV[7] - 1, 123, 0)
    return
  end
  if e.id < 17 or e.id > 32 or e.page >= SETP then return end
  play((e.page - 1) * 16 + e.id - 16)
end

function page.onPageChange(prev, curr)
  drawAll(curr)                       -- getPage() may not report curr yet
end

local function pull()
  for k = 1, 8 do
    var.register(SN[k], "int", SV[k])
    SV[k] = clamp(var.get(SN[k]), LO[k], HI[k])
  end
end

function page.onVarChange()
  offAll()
  pull()
  drawAll()
end

function page.onInit()
  pull()
  for id = 33, 40 do controller.set(id, {manual = true, v = 8192}) end
  system.setUpdateRate(20)
  drawAll()
end
