#!/usr/bin/env python3
"""Fill chords.lua with 11 pages of chords from Impressive Chords sets.

Chord sets come from the Impressive Chords module for Schwung
(github.com/mestela/schwung-impressive-chords, src/presets/chords/*.chords).

Each page gets 16 chords from one set: NAME takes chords 0-15, NAME:32 starts at
chord 32. Chord names are worked out here, offline, so the script only has to
look them up. The data block in chords.lua (between the BEGIN/END markers) is
rewritten in place.

usage: make_chords.py chords.lua SET[:START] ... (up to 11 sets)
"""
import os
import re
import sys
import urllib.request

RAW = "https://raw.githubusercontent.com/mestela/schwung-impressive-chords/main/src/presets/chords/{}.chords"
CACHE = os.path.join(os.path.dirname(__file__), "..", "build", "chordsets")

# Suffix templates: intervals above the root. The 5th is optional in matching.
# Labels are 4 characters, so the script writes minor chords with a lowercase
# root and drops the "m" (F#m11 -> "f#11"); suffixes here keep the "m".
TEMPLATES = [
    ("", {0, 4, 7}), ("m", {0, 3, 7}), ("o", {0, 3, 6}), ("+", {0, 4, 8}),
    ("s2", {0, 2, 7}), ("s4", {0, 5, 7}), ("6", {0, 4, 7, 9}), ("m6", {0, 3, 7, 9}),
    ("7", {0, 4, 7, 10}), ("M7", {0, 4, 7, 11}), ("m7", {0, 3, 7, 10}),
    ("mM7", {0, 3, 7, 11}), ("h7", {0, 3, 6, 10}), ("o7", {0, 3, 6, 9}),
    ("7s", {0, 5, 7, 10}), ("a9", {0, 2, 4, 7}), ("ma9", {0, 2, 3, 7}),
    ("69", {0, 2, 4, 7, 9}), ("m69", {0, 2, 3, 7, 9}), ("9", {0, 2, 4, 7, 10}),
    ("M9", {0, 2, 4, 7, 11}), ("m9", {0, 2, 3, 7, 10}), ("9s", {0, 2, 5, 7, 10}),
    ("11", {0, 2, 4, 5, 7, 10}), ("m11", {0, 2, 3, 5, 7, 10}), ("M11", {0, 2, 4, 5, 7, 11}),
    ("13", {0, 2, 4, 7, 9, 10}), ("m13", {0, 2, 3, 7, 9, 10}), ("M13", {0, 2, 4, 7, 9, 11}),
    ("7b9", {0, 1, 4, 7, 10}), ("7#9", {0, 3, 4, 7, 10}), ("M7#11", {0, 4, 6, 7, 11}),
    ("m7b9", {0, 1, 3, 7, 10}), ("5", {0, 7}),
]
SUF = [s for s, _ in TEMPLATES]


def name_chord(notes):
    """Return (root pitch class, suffix index) or None if nothing fits."""
    pcs = {n % 12 for n in notes}
    bass = min(notes) % 12
    best = None
    for root in sorted(pcs):
        rel = {(p - root) % 12 for p in pcs}
        for i, (_, tpl) in enumerate(TEMPLATES):
            required = tpl - {7} if len(tpl) > 2 else tpl
            if required <= rel and rel <= tpl:
                # prefer: bass is the root, fewer missing tones, simpler names
                score = (root == bass) * 10 - len(tpl - rel) * 3 - len(tpl) * 0.1
                if best is None or score > best[0]:
                    best = (score, root, i)
    return (best[1], best[2]) if best else None


def fetch(name):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, name + ".chords")
    if not os.path.exists(path):
        with urllib.request.urlopen(RAW.format(name)) as r:
            open(path, "wb").write(r.read())
    title, chords = name, {}
    for line in open(path, encoding="utf-8"):
        m = re.match(r"\s*Name:\s*(.+)", line)
        if m:
            title = m.group(1).strip()
        m = re.match(r"\s*(\d+):\s*([\d,\s]+)", line)
        if m:
            chords[int(m.group(1))] = sorted({int(x) for x in m.group(2).split(",") if x.strip()})
    return title, chords


def short(title):
    words = re.findall(r"[A-Za-z0-9]+", title)
    s = words[0][:4] if len(words) == 1 else "".join(w[:2] for w in words[:2])
    return s[:1].upper() + s[1:4]


def main():
    target, specs = sys.argv[1], sys.argv[2:]
    if not 1 <= len(specs) <= 11:
        sys.exit("give 1-11 chord sets")
    tokens, titles, pages, unnamed = [], [], [], 0
    for spec in specs:
        name, _, start = spec.partition(":")
        title, chords = fetch(name)
        start = int(start or 0)
        titles.append(title[:15])
        pages.append(short(title))
        for k in range(start, start + 16):
            notes = [n for n in chords.get(k, []) if 22 <= n <= 115]
            if not notes:
                tokens.append("!!")                        # empty pad
                continue
            nm = name_chord(notes)
            if nm is None:
                unnamed += 1
            root, suf = nm if nm else (None, 0)
            tokens.append(("-" if root is None else chr(65 + root)) + chr(48 + suf)
                          + "".join(chr(n + 11) for n in notes))
    block = ("-- BEGIN CHORD DATA (generated by tools/make_chords.py)\n"
             f"-- pages: {','.join(pages + ['-'] * (11 - len(pages)) + ['Set'])}\n"
             f"local D = [=[{' '.join(tokens)}]=]\n"
             f"local T = [=[{'|'.join(titles)}]=]\n"
             "local SUF = {" + ", ".join(f'"{s}"' for s in SUF) + "}\n"
             "-- END CHORD DATA")
    src = open(target, encoding="utf-8").read()
    src, n = re.subn(r"-- BEGIN CHORD DATA.*?-- END CHORD DATA", lambda _: block, src, flags=re.S)
    if n != 1:
        sys.exit("chord data markers not found in " + target)
    open(target, "w", encoding="utf-8").write(src)
    print(f"{len(specs)} pages, {len(tokens)} pads, {unnamed} chords without a name; "
          f"data {len(block)} bytes")
    print("pages:", ", ".join(f"{p} ({t})" for p, t in zip(pages, titles)))


if __name__ == "__main__":
    main()
